import { Language } from 'types/infographTypes';

/**
 * Supported languages for the infograph.
 *
 * Primarily used to indicate which language to use for accessibility readers.
 */
const LANGUAGES: Language[] = [
  { iso639_1_Code: 'af', displayName: 'Afrikaans' },
  { iso639_1_Code: 'sq', displayName: 'Albanian' },
  { iso639_1_Code: 'am', displayName: 'Amharic' },
  { iso639_1_Code: 'ar', displayName: 'Arabic' },
  { iso639_1_Code: 'hy', displayName: 'Armenian' },
  { iso639_1_Code: 'as', displayName: 'Assamese' },
  { iso639_1_Code: 'ay', displayName: 'Aymara' },
  { iso639_1_Code: 'az', displayName: 'Azerbaijani' },
  { iso639_1_Code: 'bm', displayName: 'Bambara' },
  { iso639_1_Code: 'eu', displayName: 'Basque' },
  { iso639_1_Code: 'be', displayName: 'Belarusian' },
  { iso639_1_Code: 'bn', displayName: 'Bengali' },
  { iso639_1_Code: 'bho', displayName: 'Bhojpuri' },
  { iso639_1_Code: 'bs', displayName: 'Bosnian' },
  { iso639_1_Code: 'bg', displayName: 'Bulgarian' },
  { iso639_1_Code: 'ca', displayName: 'Catalan' },
  { iso639_1_Code: 'ceb', displayName: 'Cebuano' },
  { iso639_1_Code: 'zh-CN', displayName: 'Chinese (Simplified)' },
  { iso639_1_Code: 'zh-TW', displayName: 'Chinese (Traditional)' },
  { iso639_1_Code: 'co', displayName: 'Corsican' },
  { iso639_1_Code: 'hr', displayName: 'Croatian' },
  { iso639_1_Code: 'cs', displayName: 'Czech' },
  { iso639_1_Code: 'da', displayName: 'Danish' },
  { iso639_1_Code: 'dv', displayName: 'Dhivehi' },
  { iso639_1_Code: 'doi', displayName: 'Dogri' },
  { iso639_1_Code: 'nl', displayName: 'Dutch' },
  { iso639_1_Code: 'en', displayName: 'English' },
  { iso639_1_Code: 'eo', displayName: 'Esperanto' },
  { iso639_1_Code: 'et', displayName: 'Estonian' },
  { iso639_1_Code: 'ee', displayName: 'Ewe' },
  { iso639_1_Code: 'fil', displayName: 'Filipino' },
  { iso639_1_Code: 'fi', displayName: 'Finnish' },
  { iso639_1_Code: 'fr', displayName: 'French' },
  { iso639_1_Code: 'fy', displayName: 'Frisian' },
  { iso639_1_Code: 'gl', displayName: 'Galician' },
  { iso639_1_Code: 'ka', displayName: 'Georgian' },
  { iso639_1_Code: 'de', displayName: 'German' },
  { iso639_1_Code: 'el', displayName: 'Greek' },
  { iso639_1_Code: 'gn', displayName: 'Guarani' },
  { iso639_1_Code: 'gu', displayName: 'Gujarati' },
  { iso639_1_Code: 'ht', displayName: 'Haitian Creole' },
  { iso639_1_Code: 'ha', displayName: 'Hausa' },
  { iso639_1_Code: 'haw', displayName: 'Hawaiian' },
  { iso639_1_Code: 'he', displayName: 'Hebrew' },
  { iso639_1_Code: 'hi', displayName: 'Hindi' },
  { iso639_1_Code: 'hmn', displayName: 'Hmong' },
  { iso639_1_Code: 'hu', displayName: 'Hungarian' },
  { iso639_1_Code: 'is', displayName: 'Icelandic' },
  { iso639_1_Code: 'ig', displayName: 'Igbo' },
  { iso639_1_Code: 'ilo', displayName: 'Ilocano' },
  { iso639_1_Code: 'id', displayName: 'Indonesian' },
  { iso639_1_Code: 'ga', displayName: 'Irish' },
  { iso639_1_Code: 'it', displayName: 'Italian' },
  { iso639_1_Code: 'ja', displayName: 'Japanese' },
  { iso639_1_Code: 'jv', displayName: 'Javanese' },
  { iso639_1_Code: 'kn', displayName: 'Kannada' },
  { iso639_1_Code: 'kk', displayName: 'Kazakh' },
  { iso639_1_Code: 'km', displayName: 'Khmer' },
  { iso639_1_Code: 'rw', displayName: 'Kinyarwanda' },
  { iso639_1_Code: 'gom', displayName: 'Konkani' },
  { iso639_1_Code: 'ko', displayName: 'Korean' },
  { iso639_1_Code: 'kri', displayName: 'Krio' },
  { iso639_1_Code: 'ku', displayName: 'Kurdish' },
  { iso639_1_Code: 'ckb', displayName: 'Kurdish (Sorani)' },
  { iso639_1_Code: 'ky', displayName: 'Kyrgyz' },
  { iso639_1_Code: 'lo', displayName: 'Lao' },
  { iso639_1_Code: 'la', displayName: 'Latin' },
  { iso639_1_Code: 'lv', displayName: 'Latvian' },
  { iso639_1_Code: 'ln', displayName: 'Lingala' },
  { iso639_1_Code: 'lt', displayName: 'Lithuanian' },
  { iso639_1_Code: 'lg', displayName: 'Luganda' },
  { iso639_1_Code: 'lb', displayName: 'Luxembourgish' },
  { iso639_1_Code: 'mk', displayName: 'Macedonian' },
  { iso639_1_Code: 'mai', displayName: 'Maithili' },
  { iso639_1_Code: 'mg', displayName: 'Malagasy' },
  { iso639_1_Code: 'ms', displayName: 'Malay' },
  { iso639_1_Code: 'ml', displayName: 'Malayalam' },
  { iso639_1_Code: 'mt', displayName: 'Maltese' },
  { iso639_1_Code: 'mi', displayName: 'Maori' },
  { iso639_1_Code: 'mr', displayName: 'Marathi' },
  { iso639_1_Code: 'mni-Mtei', displayName: 'Meiteilon' },
  { iso639_1_Code: 'lus', displayName: 'Mizo' },
  { iso639_1_Code: 'mn', displayName: 'Mongolian' },
  { iso639_1_Code: 'my', displayName: 'Myanmar' },
  { iso639_1_Code: 'ne', displayName: 'Nepali' },
  { iso639_1_Code: 'no', displayName: 'Norwegian' },
  { iso639_1_Code: 'ny', displayName: 'Nyanja' },
  { iso639_1_Code: 'or', displayName: 'Odia' },
  { iso639_1_Code: 'om', displayName: 'Oromo' },
  { iso639_1_Code: 'ps', displayName: 'Pashto' },
  { iso639_1_Code: 'fa', displayName: 'Persian' },
  { iso639_1_Code: 'pl', displayName: 'Polish' },
  { iso639_1_Code: 'pt', displayName: 'Portuguese' },
  { iso639_1_Code: 'pa', displayName: 'Punjabi' },
  { iso639_1_Code: 'qu', displayName: 'Quechua' },
  { iso639_1_Code: 'ro', displayName: 'Romanian' },
  { iso639_1_Code: 'ru', displayName: 'Russian' },
  { iso639_1_Code: 'sm', displayName: 'Samoan' },
  { iso639_1_Code: 'sa', displayName: 'Sanskrit' },
  { iso639_1_Code: 'gd', displayName: 'Scots Gaelic' },
  { iso639_1_Code: 'nso', displayName: 'Sepedi' },
  { iso639_1_Code: 'sr', displayName: 'Serbian' },
  { iso639_1_Code: 'st', displayName: 'Sesotho' },
  { iso639_1_Code: 'sn', displayName: 'Shona' },
  { iso639_1_Code: 'sd', displayName: 'Sindhi' },
  { iso639_1_Code: 'si', displayName: 'Sinhala' },
  { iso639_1_Code: 'sk', displayName: 'Slovak' },
  { iso639_1_Code: 'sl', displayName: 'Slovenian' },
  { iso639_1_Code: 'so', displayName: 'Somali' },
  { iso639_1_Code: 'es', displayName: 'Spanish' },
  { iso639_1_Code: 'su', displayName: 'Sundanese' },
  { iso639_1_Code: 'sw', displayName: 'Swahili' },
  { iso639_1_Code: 'sv', displayName: 'Swedish' },
  { iso639_1_Code: 'tl', displayName: 'Tagalog (Filipino)' },
  { iso639_1_Code: 'tg', displayName: 'Tajik' },
  { iso639_1_Code: 'ta', displayName: 'Tamil' },
  { iso639_1_Code: 'tt', displayName: 'Tatar' },
  { iso639_1_Code: 'te', displayName: 'Telugu' },
  { iso639_1_Code: 'th', displayName: 'Thai' },
  { iso639_1_Code: 'ti', displayName: 'Tigrinya' },
  { iso639_1_Code: 'ts', displayName: 'Tsonga' },
  { iso639_1_Code: 'tr', displayName: 'Turkish' },
  { iso639_1_Code: 'tk', displayName: 'Turkmen' },
  { iso639_1_Code: 'ak', displayName: 'Twi (Akan)' },
  { iso639_1_Code: 'uk', displayName: 'Ukrainian' },
  { iso639_1_Code: 'ur', displayName: 'Urdu' },
  { iso639_1_Code: 'ug', displayName: 'Uyghur' },
  { iso639_1_Code: 'uz', displayName: 'Uzbek' },
  { iso639_1_Code: 'vi', displayName: 'Vietnamese' },
  { iso639_1_Code: 'cy', displayName: 'Welsh' },
  { iso639_1_Code: 'xh', displayName: 'Xhosa' },
  { iso639_1_Code: 'yi', displayName: 'Yiddish' },
  { iso639_1_Code: 'yo', displayName: 'Yoruba' },
  { iso639_1_Code: 'zu', displayName: 'Zulu' },
];

export { LANGUAGES };
