const DEFAULT_WIDTH = 480;
const DEFAULT_HEIGHT = 350;

const DEFAULT_BORDER_WIDTH = 0;
const DEFAULT_BORDER_COLOR = '#FFF';

export { DEFAULT_HEIGHT, DEFAULT_WIDTH, DEFAULT_BORDER_WIDTH, DEFAULT_BORDER_COLOR };
