export const connectedLineWidgets = {
  '006.g2a8vXBLDf7bSTMD7YBNLD84': {
    type: 'rectangle',
    topPx: 151,
    border: {
      color: 'black',
      style: 'solid',
      width: 0,
    },
    leftPx: 4,
    mirror: {
      isVertical: false,
      isHorizontal: false,
    },
    altText: '',
    version: 1,
    widthPx: 184,
    heightPx: 184,
    fillColor: ['#0073E6'],
    rotateDeg: 0,
    fillPercent: 0,
    isDecorative: true,
  },
  '005.bcACqKEGrHV380TCfzC06zg3': {
    type: 'straight',
    topPx: 227.5,
    endPos: {
      xPx: 339,
      yPx: 4.5,
    },
    leftPx: 188,
    altText: '',
    posList: [
      {
        xPx: 0,
        yPx: 10,
      },
      {
        xPx: 400,
        yPx: 10,
      },
    ],
    version: 1,
    widthPx: 339,
    heightPx: 20,
    startPos: {
      xPx: 0,
      yPx: 15.5,
    },
    widgetId: 'line-menu-horizontal-line',
    rotateDeg: 0,
    startPort: {
      side: 'EAST',
      widgetId: '006.g2a8vXBLDf7bSTMD7YBNLD84',
      alignment: 'CENTER',
    },
    midPosList: [],
    strokeColor: '#000',
    strokeWidth: 3,
    isDecorative: true,
    endArrowStyle: 'none',
    strokeDashType: 'solid',
    startArrowStyle: 'none',
    endPort: {
      widgetId: '006.jlz1bzD5UmLDu8pCMz5Lonsc',
      alignment: 'CENTER',
      side: 'WEST',
    },
  },
  '006.jlz1bzD5UmLDu8pCMz5Lonsc': {
    type: 'rectangle',
    topPx: 140,
    border: {
      color: 'black',
      style: 'solid',
      width: 0,
    },
    leftPx: 527,
    mirror: {
      isVertical: false,
      isHorizontal: false,
    },
    altText: '',
    version: 1,
    widthPx: 184,
    heightPx: 184,
    fillColor: ['#0073E6'],
    rotateDeg: 0,
    fillPercent: 0,
    isDecorative: true,
  },
};

export const nonConnectedLineWidgets = {
  '006.g2a8vXBLDf7bSTMD7YBNLD84': {
    type: 'rectangle',
    topPx: 60.93000000000001,
    border: {
      color: 'black',
      style: 'solid',
      width: 0,
    },
    leftPx: 11,
    mirror: {
      isVertical: false,
      isHorizontal: false,
    },
    altText: '',
    version: 1,
    widthPx: 184,
    heightPx: 184,
    fillColor: ['#0073E6'],
    rotateDeg: 0,
    fillPercent: 0,
    isDecorative: true,
  },
  '005.bcACqKEGrHV380TCfzC06zg3': {
    type: 'straight',
    topPx: 196.929771875,
    endPos: {
      xPx: 139,
      yPx: 21.070456250000007,
    },
    leftPx: 319,
    altText: '',
    endPort: null,
    posList: [
      {
        xPx: 0,
        yPx: 10,
      },
      {
        xPx: 400,
        yPx: 10,
      },
    ],
    version: 1,
    widthPx: 139,
    heightPx: 21.070456250000007,
    startPos: {
      xPx: 0,
      yPx: 0,
    },
    widgetId: 'line-menu-horizontal-line',
    rotateDeg: 0,
    startPort: null,
    midPosList: [],
    strokeColor: '#000',
    strokeWidth: 3,
    isDecorative: true,
    endArrowStyle: 'none',
    strokeDashType: 'solid',
    startArrowStyle: 'none',
  },
  '006.jlz1bzD5UmLDu8pCMz5Lonsc': {
    type: 'rectangle',
    topPx: 156.93,
    border: {
      color: 'black',
      style: 'solid',
      width: 0,
    },
    leftPx: 588,
    mirror: {
      isVertical: false,
      isHorizontal: false,
    },
    altText: '',
    version: 1,
    widthPx: 184,
    heightPx: 184,
    fillColor: ['#0073E6'],
    rotateDeg: 0,
    fillPercent: 0,
    isDecorative: true,
  },
};
